# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          sudo apt install libfontconfig1-dev libfreetype-dev libgtk-3-dev libx11-dev libx11-xcb-dev libxcb-cursor-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xkb-dev libxcb1-dev libxext-dev libxfixes-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev
          python3 -m venv .
          source bin/activate
          cd src
          pip install -r requirements.txt
          pyinstaller decryptor.py

      - uses: actions/upload-artifact@v4
        with:
          name: dist-linux
          path: src/dist
          
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        shell: cmd
        run: |
          python3 -m venv .
          Scripts\activate.bat
          cd src
          pip install -r requirements.txt
          pyinstaller decryptor.py

      - uses: actions/upload-artifact@v4
        with:
          name: dist-windows
          path: src/dist
